require('base.plugins.interface.lualine')
require('base.plugins.interface.dashboard')
require('base.plugins.interface.noice')
require('base.plugins.interface.corn')
require('base.plugins.interface.notify')
